Limit RoleSessionName length to avoid API errors
iamarkadyt/aws-auth pull request #6
Opened 2022-02-28 18:07 UTC by DocLM

Hi @iamarkadyt,
AWS Organizations suggest `OrganizationAccountAccessRole` as default role name, when calling STS endpoint to assume the role on other accounts the naming convention in aws-auth can reach RoleSessionName field limits of 64 characters.

In order to avoid this issue I propose to limit the first part of the field generation to ensure that the field name does not exceed the length limit.

2022-03-01 01:25 UTC, iamarkadyt requested changes

2022-03-01 01:25 UTC, iamarkadyt commented on src/actions/login.js
> -        ;({ Credentials } = await STS.assumeRole(stsParams).promise())
Sorry for a nit pick, but let's clean up this whitespace

2022-03-01 01:25 UTC, iamarkadyt commented on src/actions/login.js
> +        RoleSessionName: `${session.slice(0, 64 - now.length - 1)}-${now}`,
I like this :+1:, I think it's a great catch. But I'd like to see a reference to this in AWS API documentation. Do you have a link?

2022-03-01 01:26 UTC, iamarkadyt commented on src/actions/login.js
> +        ; ({ Credentials } = await STS.assumeRole(stsParams).promise())
Nit. Let's remove this white space.

2022-03-01 01:27 UTC, iamarkadyt commented on src/actions/login.js
> +        RoleSessionName: `${session.slice(0, 64 - now.length - 1)}-${now}`,
Also let's rename variables as follows:
`now` -> `timestamp`
`session` -> `userInfo`

2022-03-01 01:28 UTC, iamarkadyt commented
@DocLM thanks for your contribution, left you a few comments.

2022-03-01 06:45 UTC, DocLM commented on src/actions/login.js
> +        RoleSessionName: `${session.slice(0, 64 - now.length - 1)}-${now}`,
Of course, I found it in the API docs here: https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRole.html

Under _Requested Parameters_ section there is a part for `RoleSessionName` parameter with the following constraints:
- Length Constraints: Minimum length of 2. Maximum length of 64.
- Pattern: `[\w+=,.@-]*`

2022-03-01 06:47 UTC, DocLM commented on src/actions/login.js
> +        ; ({ Credentials } = await STS.assumeRole(stsParams).promise())
Sorry, probably is VSCode autoformat feature. I removed the extra whitespace.

2022-03-01 06:52 UTC, DocLM commented
@iamarkadyt I addressed you comments, should be ready to merge

2022-03-02 03:44 UTC, merged

2022-03-02 03:44 UTC, iamarkadyt commented
Thanks @DocLM :+1:. Merged.